inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/test/**/*'
    - 'node_modules/**/*'

# 日本語のコメントを OK とする
Style/AsciiComments:
  Enabled: false

# 一行に 120 文字まで書いても OK とする
Layout/LineLength:
  Max: 120

# class documentation commentのアラートを出さない
Documentation:
  Enabled: false
