inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  # Supported versions: 2.4, 2.5, 2.6, 2.7, 3.0
  NewCops: enable
  Exclude:
    - 'spec/test/**/*'
    - 'node_modules/**/*'

# 日本語のコメントを OK とする
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockComments:
  Enabled: false
# 一行に 120 文字まで書いても OK とする
Layout/LineLength:
  Max: 120

# class documentation commentのアラートを出さない
Documentation:
  Enabled: false
